# Generated by Django 3.1.1 on 2020-10-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20201007_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancost',
            name='plans',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='costs',
            field=models.ManyToManyField(blank=True, help_text='the subscription plan for these cost details', related_name='plans', to='subscriptions.PlanCost'),
        ),
        migrations.DeleteModel(
            name='PlanCostLink',
        ),
    ]
